source 'https://github.com/CocoaPods/Specs.git'

target 'MDResourceManager', :exclusive => true do
  pod "MDResourceManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MDResourceManager", :path => "../"
  pod 'OCMock' 
end