source 'https://github.com/CocoaPods/Specs.git'

target 'MDResourceManager', :exclusive => true do
  pod "MDResourceManager"
end

target 'Tests', :exclusive => true do
  pod "MDResourceManager",
  pod 'OCMock' 
end